let suggestions = [
    "css",
    "job",
    "code",
    "react",
    "movies",
    "youtube",
    "javascript",
    "opportunity",
    "what is css",
    "programming",
    "freecodecamp",
    "landing pages",
    "dom scripting",
    "new 2022 movies",
    "simple react apps",
    "how to code react",
    "funny youtube videos",
    "free coding tutorials",
    "new job opportunities",
    "freelancing platforms",
    "best javascript books",
    "functional programming",
    "beautiful website designs",
    "advanced javascript tutorials"
];